### ISSUE TITLE
[Bug] Does not work with twisted 24.10.0+ at least on python 3.12

### ISSUE THREAD

**Issue by MVKozlov** [pryorda/vmware_exporter#399]
**Warning for anyone doing a new install**

version 0.18.4
```
Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/local/bin/vmware_exporter/.venv/lib/python3.12/site-packages/twisted/internet/defer.py", line 1088, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "/usr/local/bin/vmware_exporter/.venv/lib/python3.12/site-packages/vmware_exporter/defer.py", line 52, in callback
    self.callbacks.pop(0).callback(result)
builtins.AttributeError: 'tuple' object has no attribute 'callback'
```

last working public version `twisted 24.7.0`

**Comment by barborek** [comment]
hi,

if you use twisted version with 24.3.0, your problem can fix.

**Comment by barborek** [comment]
In addition to what you wrote, I can give the information to overcome this bug.

change twisted version in the requirements.txt to fix this problem:


```
prometheus-client==0.0.19
pytz
pyvmomi>=6.5
twisted==24.7.0
pyyaml>=5.1
service-identity
```
and then rebuild docker image.
